export interface PortfolioProject {
  slug: string;
  name: string;
  category: "sistemas" | "ecommerce" | "municipal" | "saas" | "web" | "redes";
  client: string;
  description: string;
  problem: string;
  solution: string;
  technologies: string[];
  image?: string;
  url?: string;
  results?: string;
}

export const portfolio: PortfolioProject[] = [
  {
    slug: "menulia",
    name: "MenuIA",
    category: "saas",
    client: "Restaurantes del NEA",
    description: "Menú digital inteligente con IA para restaurantes",
    problem: "Restaurantes necesitaban actualizar su menú constantemente y ofrecer opciones sin contacto físico.",
    solution: "Desarrollamos un sistema de menú digital con IA que permite actualizaciones en tiempo real y pedidos directamente desde el teléfono del cliente.",
    technologies: ["Next.js", "TypeScript", "IA", "PWA"],
    image: "/images/portfolio/menulia.jpg",
    url: "https://menulia.devbyte.com.ar",
    results: "Reducción del 40% en tiempos de atención",
  },
  {
    slug: "gorilagym",
    name: "GorilaGym",
    category: "sistemas",
    client: "Gorila Gym Resistencia",
    description: "Sistema de gestión integral para gimnasios",
    problem: "Gestión manual de membresías, pagos y asistentes causaba errores y pérdida de tiempo.",
    solution: "Sistema completo con registro de asistentes, gestión de membresías, recordatorios automáticos y dashboard de estadísticas.",
    technologies: ["Next.js", "Prisma", "PostgreSQL", "Tailwind CSS"],
    results: "30% de aumento en renovaciones de membresía",
  },
  {
    slug: "liga-makalle",
    name: "Liga Makallé",
    category: "sistemas",
    client: "Liga Makallé de Fútbol",
    description: "Sistema de venta de entradas y gestión de partidos",
    problem: "Venta manual de entradas y falta de control en los partidos de la liga.",
    solution: "Plataforma de venta online de entradas con código QR, sistema de control de acceso y gestión de partidos.",
    technologies: ["Next.js", "TypeScript", "QR", "Pagos Online"],
    results: "100% de venta online, sin fraude en entradas",
  },
  {
    slug: "evenser",
    name: "Evenser",
    category: "sistemas",
    client: "Evenser Servicios Funerarios",
    description: "Sistema de gestión para empresas funerarias",
    problem: "Falta de sistematización en la gestión de servicios funerarios y comunicación con familias.",
    solution: "Sistema de gestión de servicios, agenda de velatorios y comunicación con familiares.",
    technologies: ["Next.js", "Prisma", "PostgreSQL"],
  },
  {
    slug: "turismo-la-escondida",
    name: "Turismo La Escondida",
    category: "municipal",
    client: "Municipalidad de La Escondida",
    description: "Portal web turístico del municipio",
    problem: "El municipio necesitaba difusión de sus atractivos turísticos y servicios.",
    solution: "Portal turístico con información de lugares, eventos, servicios municipales y directorio de emprendedores locales.",
    technologies: ["Next.js", "TypeScript", "CMS"],
  },
  {
    slug: "carnavales-makalle",
    name: "Carnavales Makallé",
    category: "ecommerce",
    client: "Comité de Carnavales de Makallé",
    description: "Sistema de venta de entradas para carnavales",
    problem: "Venta de entradas manual y largas filas en los eventos.",
    solution: "Sistema de preventa online de entradas con retirada en puntos de venta locales.",
    technologies: ["Next.js", "Mercado Pago", "TypeScript"],
    results: "Venta de +5000 entradas online",
  },
  {
    slug: "uegp-162",
    name: "Panel UEGP 162 + Campus",
    category: "sistemas",
    client: "UEGP 162",
    description: "Panel de administración educativa y campus virtual",
    problem: "La institución necesitaba gestionar alumnos, cursos y materiales de forma centralizada.",
    solution: "Sistema completo con panel administrativo, campus virtual para estudiantes, gestión de notas y asistencia.",
    technologies: ["Next.js", "TypeScript", "Prisma", "PostgreSQL"],
    results: "Gestión de +500 estudiantes",
  },
  {
    slug: "sa-ideas-creativas",
    name: "SA Ideas Creativas",
    category: "ecommerce",
    client: "SA Ideas Creativas",
    description: "Tienda online para emprendimiento regional",
    problem: "Negocio de artesanías necesitaba vender sus productos online de forma directa.",
    solution: "E-commerce completo con catálogo de productos, carrito de compras, integración con Mercado Pago y gestión de pedidos.",
    technologies: ["Next.js", "TypeScript", "Mercado Pago", "Tailwind CSS"],
    results: "Incremento del 60% en ventas",
  },
  {
    slug: "passwordwifi",
    name: "P@sswordWifi ISP",
    category: "web",
    client: "P@sswordWifi",
    description: "Página web y panel de administración para ISP",
    problem: "Proveedor de internet necesitaba presencia web profesional y sistema de gestión de clientes.",
    solution: "Sitio web corporativo con información de planes y panel de administración para gestionar clientes, pedidos y facturación.",
    technologies: ["Next.js", "TypeScript", "Prisma", "PostgreSQL"],
  },
  {
    slug: "aberka-aberturas",
    name: "Aberka Aberturas",
    category: "sistemas",
    client: "Aberka Aberturas",
    description: "Webapp y gestión de ventas para empresa de aberturas",
    problem: "Empresa de ventanas y puertas necesitaba digitalizar su proceso de ventas y gestión de presupuestos.",
    solution: "Aplicación web para gestión de presupuestos, seguimiento de obras, control de inventario y generación de órdenes de trabajo.",
    technologies: ["Next.js", "TypeScript", "Prisma", "PostgreSQL"],
    results: "Reducción del 50% en tiempo de gestión de presupuestos",
  },
  {
    slug: "devbyte-pedidos",
    name: "DevByte Pedidos",
    category: "sistemas",
    client: "DevByte",
    description: "Webapp para gestión de pedidos y envíos locales",
    problem: "Necesidad de gestionar pedidos locales y seguimiento de envíos en la zona.",
    solution: "Sistema de gestión de pedidos con tracking de estados, generación de etiquetas y administración de mensajeros.",
    technologies: ["Next.js", "TypeScript", "Prisma", "PostgreSQL"],
  },
  {
    slug: "profesionalesapp",
    name: "ProfesionalesAPP",
    category: "saas",
    client: "Bolsa de trabajo local",
    description: "Webapp de bolsa de trabajo para profesionales del NEA",
    problem: "Trabajadores locales y empresas necesitaban un punto de encuentro para oportunidades laborales en la región.",
    solution: "Plataforma donde profesionales cargan su CV y empresas publican búsquedas. Sistema de postulación y mensajería interna.",
    technologies: ["Next.js", "TypeScript", "Prisma", "PostgreSQL"],
    results: "+200 profesionales registrados",
  },
  {
    slug: "forcelatam",
    name: "ForceLatam",
    category: "sistemas",
    client: "ForceLatam",
    description: "Webapp de gestión empresarial integral",
    problem: "Organización necesitaba herramienta para coordinar equipos y gestionar proyectos.",
    solution: "Sistema integral con gestión de equipos, proyectos, documentos y comunicación interna.",
    technologies: ["Next.js", "TypeScript", "Prisma", "PostgreSQL"],
  },
];